### ISSUE TITLE
Not support ODEXED system?

### ISSUE THREAD

**Issue by liwanglin12** [Magisk-Modules-Repo/MagicGApps#1]
Before the version which need manually download GAPPS , this Module work normally.
But now it doesn't work..

I don't know what details should be provided so just say if necessary!

**Comment by VR-25** [comment]
Well, I think you're talking about "signature spoofing" only. If you got an installations error saying just that, then don't worry. In the new version, signature spoofing is disabled by default. "pm grant" is used instead to prevent FCs. So, whether your ROM is odexed or deodexed doesn't matter. You should have no issues now.

**Comment by liwanglin12** [comment]
But I am 100% sure the notice is 'NOT SUPPORT ODEXED SYSTEM'....

I will try again later and provide screenshot.

**Comment by liwanglin12** [comment]
I use Magic GAPPS with open GAPPS nano 0923 Android 7.1 arm64 version

**Comment by liwanglin12** [comment]
🤦so sorry, before "ODEXED " error, it has a signature spoofing error too.

I tried 0926 Magic GAPPS,but recovery told me "file is broken". I am trying to re-downlaoad it and try again.

Thanks for help!

**Comment by VR-25** [comment]
Download from the official XDA thread for now (link is on the README). For some reason, the downloaded file size is 0 Bytes. That's why it's failing.

**Comment by liwanglin12** [comment]
I downloaded Magic GAPPS in Github yesterday and successed installation.

But openGAPPS have issue on MIUI system , will caused Google Play FC.

stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5180)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5412)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6357)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
