### ISSUE TITLE
Google Service Crashes due to the "Missing" PrebuiltGmsCore.apk

### ISSUE THREAD

**Issue by Goshin** [Magisk-Modules-Repo/MagicGApps#3]
Android 7.1 with GApps (nano arm 2017/10/08)

Some of the GApps work fine, including login and sync.

But the Google Service keeps crashing and alerting, I captured the log when the Google Service stopped and tried to restart.

```
10-23 19:38:14.737  1069  3268 I ActivityManager: Killing 15861:com.google.android.gms.unstable/u0a93 (adj 0): crash
10-23 19:38:14.737  1069  3268 D ActivityManager: cleanUpApplicationRecord -- 15861
10-23 19:38:14.738  1069  3268 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.droidguard.DroidGuardService in 1000ms
10-23 19:38:14.742   329   561 D audio_hw_primary: select_devices: done
10-23 19:38:14.752  1069  6551 D OpenGLRenderer: endAllActiveAnimators on 0x944bfd80 (RippleDrawable) with handle 0x99827ec0
10-23 19:38:14.760  1069 14896 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@275c49f attribute=null, token = android.os.BinderProxy@487ce88
10-23 19:38:14.900  1069  1104 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-23 19:38:14.955  1069  1323 I LIGHT   : [LightSensor.cpp: processEvent: 331] light value is 221
10-23 19:38:15.461  1069  1323 I LIGHT   : [LightSensor.cpp: processEvent: 331] light value is 222
10-23 19:38:15.778  1069  1097 I ActivityManager: Start proc 15892:com.google.android.gms.unstable/u0a93 for service com.google.android.gms/.droidguard.DroidGuardService
10-23 19:38:15.852   215   265 I Magisk  : proc_monitor: com.google.android.gms.unstable (PID=15892 ns=mnt:[4026534549])
10-23 19:38:15.853 15897 15897 I Magisk  : hide_daemon: Permissive detected, hide the state
10-23 19:38:15.962  1069  1323 I LIGHT   : [LightSensor.cpp: processEvent: 331] light value is 222
10-23 19:38:16.003 15892 15892 W System  : ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk
10-23 19:38:16.004 15892 15892 W System  : ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/arm
10-23 19:38:16.006 15892 15892 W linker  : Warning: unable to resolve "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk": No such file or directory
10-23 19:38:16.006 15892 15892 W linker  : Warning: unable to resolve "/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk": No such file or directory
10-23 19:38:16.008 15892 15892 W asset   : Asset path /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk is neither a directory nor file (type=1).
10-23 19:38:16.009 15892 15892 E ResourcesManager: failed to add asset path /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk
10-23 19:38:16.009 15892 15892 D AndroidRuntime: Shutting down VM
10-23 19:38:16.010 15892 15892 E AndroidRuntime: FATAL EXCEPTION: main
10-23 19:38:16.010 15892 15892 E AndroidRuntime: Process: com.google.android.gms.unstable, PID: 15892
10-23 19:38:16.010 15892 15892 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5165)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5390)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
10-23 19:38:16.010 15892 15892 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
10-23 19:38:16.013  1069  3251 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:375 com.android.server.am.AppErrors.crashApplication:309 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13757 com.android.server.am.ActivityManagerService.handleApplicationCrash:13739 
10-23 19:38:16.065  1069  6551 I OpenGLRenderer: Initialized EGL, version 1.4
10-23 19:38:16.065  1069  6551 D OpenGLRenderer: Swap behavior 1
10-23 19:38:16.471  1069  1323 I LIGHT   : [LightSensor.cpp: processEvent: 331] light value is 222
10-23 19:38:16.975  1069  1323 I LIGHT   : [LightSensor.cpp: processEvent: 331] light value is 221
```

Seems the `/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk` cannot be found by the system. But it is still visible in file managers and terminals. Is it a mounting issue of the Magisk?

By the way, the permission granting while installing broke my permission settings for the other apps. Is it intended or just a known side effect?

**Comment by Jaitsu** [comment]
Same exact issues here - Google Services crashes constantly, everything else (except Calendar, which also occasionally seems to crash) is fine, app permissions broken.

**Comment by VR-25** [comment]
It's been a while! I forgot about this post -- my bad.

It seems this issue is not related to the module at all, but rather Magisk itself or something else (ongoing investigation). So far, I've tested signature spoofing, permissions granting, WebView workaround -- none of which helped.

Missing `/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk` -- no such issue for me, or I didn't stumble upon this enough times.

In regards to permission granting, that's odd. The command used (pm grant) isn't supposed to mess with other apps in the way it was implemented.

This issue will remain open -- waiting for some light.

**Comment by turkteam321** [comment]
Oluyormu?

**Comment by turkteam321** [comment]
Install apk ?

**Comment by hkrware** [comment]
I copy PrebuiltGmsCore, Provision and ManagedProvisioning folders over in both the Magisk MagicGApps system and the real system just to make sure and it fixes all problems (AICP ROM)

**Comment by bam80** [comment]
Thanks @hkrware.
@VR-25, so what should be fix for this?

**Comment by bam80** [comment]
Thanks @hkrware I just asked what should be the fix so that it wouldn't need manually copying

**Comment by hkrware** [comment]
Sorry don't remember much on the matter.
On another note, you can just skip mounting persist since it's empty for the GApps.

**Comment by bam80** [comment]
@VR-25 , any thoughts about broken permissions?

**Comment by VR-25** [comment]
New build is up.

IMPORTANT NOTE: untill further notice, I'm only supporting official, stable Magisk versions. The reasons being, other builds are actually behind most modules issues (yes, I said "modules") and I just don't have the time anymore to play with more stuff. So, do not report issues if you're not running an official and stable Magisk version.
